project_name: orbit

before:
  hooks:
    - go mod download

builds:
  - id: orbit
    dir: ./orbit/cmd/orbit/
    binary: orbit
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/fleetdm/fleet/v4/orbit/pkg/build.Version={{.Version}}
      - -X github.com/fleetdm/fleet/v4/orbit/pkg/build.Commit={{.Commit}}
      - -X github.com/fleetdm/fleet/v4/orbit/pkg/build.Date={{.Date}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-untagged"

changelog:
  skip: true

release:
  github:
    owner: fleetdm
    name: fleet
  draft: true
  name_template: "orbit-{{ .Tag }}"
  prerelease: auto